# Generated by Django 5.0 on 2024-10-25 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('vcn_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('image', models.ImageField(upload_to='images/')),
                ('bio', models.TextField()),
                ('x_link', models.URLField()),
                ('facebook_name', models.URLField()),
                ('instagram_link', models.URLField()),
                ('linked_link', models.URLField()),
            ],
        ),
    ]
