# Generated by Django 5.0 on 2024-10-27 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='facebook_name',
            new_name='facebook_link',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='linked_link',
            new_name='linked_in_link',
        ),
    ]
